version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
      - /etc/ssl/certs:/etc/ssl/certs  # Mount the host's certs directory
      - /etc/ssl/private:/etc/ssl/private  # Mount the host's private key directory
    depends_on:
      - web1
      - web2

  web1:
    build:
      context: .
    environment:
      - PORT=8000
    expose:
      - "8000"

  web2:
    build:
      context: .
    environment:
      - PORT=8001
    expose:
      - "8001"
